from typing import Protocol


class Db_proto(Protocol):
    def init_db(self, **kwargs) -> None: ...
    def insert_tag(self, tag: str, type: str, lv: str, en: str) -> None: ...
    def delete_tag(self, tag: str) -> bool: ...
