from enum import Enum


class AlarmLanguage(Enum):
    ENGLISH = 0
    LATVIAN = 1


class AlarmType(Enum):
    UNKNOWN = 0
    SENSOR_ALARM = 1
    DEVICE_ALARM = 2
    POWER_ALARM = 3
    DIGITAL_SENSOR_ALARM = 4






empty_alarm_text = ["Alarm", "Trauksme"]

generic_phrases = {
    "oil_tank": ["oil tank", "ellas tvertne"],
    "unit_error": ["unit error", "mērvienības kļūda"],

    "alarms_al_vfd_flt": ["VFD fault", "FP kļūda"],
    "alarms_al_run_enable_missing": ["run enable missing", "nav atļaujas signāla"],
    "alarms_al_move_flt": ["control fault", "vadības kļūda"],
    "alarms_al_com_flt": ["communications fault", "komunikācijas kļūda"],

    "alarms_warn_local_cntrl": ["local control", "lokāla vadība"],
    "alarms_warn_vfd": ["VFD warning", "FP brīdinājums"],

    "energy_meter": ["energy meter", "enerģijas skaitītājs"],
    "feed_check_fault": ["extensive feed", "ilgstoša piebarošana"],
    "feed_check": ["extensive feed", "ilgstoša piebarošana"],


    "alarms_al": ["", ""],#block that calculates alarms name
    "oil_burner": ["oil burner", "ellas deglis"],
    "no_pressure_generated_error": ["no pressure generated", "nerada spiedienu"],
    "oil_supply": ["oil supply", "ellas padeve"],
    "water_tank": ["water tank", "udens tvertne"],
    "b_circuit": ["boiler circuit", "katlu loks"],
    "boiler_circuit": ["boiler circuit", "katlu loks"],
    "outside_air": ["outside air", "argaisa"],
    "flue_gas": ["flue gas", "dumgazes"],
    "water_filter": ["water filter", "udens filtrs"],
    "to_nw": ["to network", "uz tiklu"],
    "from_nw": ["from network", "no tikla"],
    "circ_pumps": ["circulation pumps", "cirkulacijas sukni"],
    "before_burner": ["before_burner pumps", "pirms degla"],
    "vfd_on": ["VFD off", "VFD izslēgts"],
    "feed_water": ["feed water", "barošanas"],
    "pump_oil": ["oil pump", "eļļas suknis"],
    "pump_glycol": ["glycol pump", "glikola sūknis"],
    "pump_circulation": ["circulation pump", "Cirkulācijas sūknis"],
    "pump_circ": ["circulation pump", "Cirkulācijas sūknis"],
    "glycol_heating": ["glycol heating", "glikola sildīšana"],
    "pump_nw": ["network pump", "tīklu sūknis"],
    "vlv_oil_heating": ["Oil heating valve", "eļļas sildīšanas vārsts"],
    "dry_run_protection": ["dry run protection", "sausumaizsardzība"],
    "t_vlv": ["temperature valve", "temperatūras vārsts"],
    "safety_plc": ["safety plc", "drošības PLC"],
    "safety_switch": ["safety switch", "drošības slēdzis"],
    "safety_sw": ["safety switch", "drošības slēdzis"],
    "fuse_ok": ["fuse tripped", "drošinātāja bojājums"],
    "fuse_OK": ["fuse tripped", "drošinātāja bojājums"],
    "oil_pumps": ["oil pumps", "eļļas sūkņi"],
    "filling_pump": ["filling pump", "pildīšanas sūknis"],
    "partial_filter": ["partial filter", "filtrs"],
    "grate_cooling": ["grate cooling", "ārdu dzesēšana"],
    "fluegas_ventilator": ["fluegas ventilator", "dūmgāzu ventilators"],
    "to_tanks": ["to tanks", "uz tvertnēm"],
    "condenser_pump": ["condenser pump", "kondensāta sūknis"],
    "compressed_air": ["compressed air", "saspiests gaiss"],
    "truck_connection": ["truck connection", "transporta pievienojums"],
    "to_truck_tanks": ["to truck tanks", "uz transporta tvertnēm"],
    "to_mdi_tanks": ["to MDI tanks", "uz MDI tvertnēm"],
    "to_polyol_tanks": ["to polyol tanks", "uz poliola tvertnēm"],
    "to_shutoff_valves": ["to shutoff valves", "uz noslēgvārstiem"],
    "shutoff_valves": ["shutoff valves", "noslēgvārsti"],
    "shutoff_valve": ["shutoff valve", "noslēgvārsts"],
    "to_mdi": ["to MDI", "uz MDI"],
    "to_polyol": ["to polyol", "uz poliola"],
    "new_bh": ["new boiler house", "jaunā katlu māja"],
    "old_bh": ["old boiler house", "vecā katlu māja"],
    "after_filling_filter": ["after filling filter", "pēc uzpildes filtra"],
    "before_filling_filter": ["before filling filter", "pirms uzpildes filtra"],
    "common_recirculation": ["common recirculation", "kopējā recirkulācija"],
    "out_max_pv_minerror": ["device running at high power not generate output",
                            "iekārta darbojas ar augstu jaudu, bet nerada rezultātu"],

    "close_torque_fault": ["close torque fault", "aizvēršanas pārslodze"],
    "open_torque_fault": ["open torque fault", "atvēršanas pārslodze"],
    "torque_fault": ["torque fault", "pārslodze"],
    "debug_transfer": ["data exchange PLC to PLC", "datu apmaiņa starp PLC"],
    "plc_com_err": ["communications fault", "komunikācijas kļūda"],
    "pump_deironer": ["deironer pump", "atdzelžotāja sūknis"],
    "pump_manufacturing": ["manufacturing pump", "ražošanas sūknis"],
    "condensate_tank": ["condensate tank", "kondensāta tvertne"],
    "to_deironer": ["to deironer", "uz atdzelžotāju"],
    "to_manufacturing": ["to manufacturing", "uz ražošanu"],
    "heating_circuit": ["heating circuit", "sildīšanas loks"],
    "motor_mixer": ["mixer motor", "miksera motors"],
    "material_line": ["material line", "materiāla līnija"],
    "weight_scale": ["svars", "svars"],
    "fault_vfd": ["VFD fault", "FP bojājums"],
    "move_fault": ["control fault", "vadības kļūda"],
    "move_flt": ["control fault", "vadības kļūda"],
    "cntrl_flt": ["control fault", "vadības kļūda"],
    "cntrl_fault": ["control fault", "vadības kļūda"],
    "fb_error": ["feedback error", "atpakaļsaites bojājums"],
    "fb_err": ["feedback error", "atpakaļsaites bojājums"],
    "FB_error": ["feedback error", "atpakaļsaites bojājums"],
    "FB_err": ["feedback error", "atpakaļsaites bojājums"],
    "warning_fault": ["warning", "brīdinājums"],
    "com_ok": ["communications fault", "komunikācijas kļūda"],
    "local_remote": ["local control enabled", "ieslēgta lokāla vadība"],
    "loc_rem": ["local control enabled", "ieslēgta lokāla vadība"],
    "run_enable_missing": ["run enable missing", "nav atļaujas signāla"],
    "run_enable": ["run enable missing", "nav atļaujas signāla"],
    "vfd_fieldbus_adapter_fault": ["VFD fieldbus adapter fault", "FP komunikācijas moduļa kļūda"],
    "state_fault": ["state fault", "pozīcijas kļūda"],
    "after_heaters": ["after heaters", "pēc sildītājiem"],
    "after_heater": ["after heater", "pēc sildītāja"],
    "material_tank": ["material tank", "materiālu tvertne"],
    "pres_sw_max": ["high pressure presostat", "augsta spiediena presostats"],
    "gas_leak_alarm": ["gas leak alarm", "gāzes noplūde"],
    "gas_leak_det": ["gas leak alarm", "gāzes noplūde"],
    "co_leak_alarm": ["CO leak alarm", "CO noplūde"],
    "co_leak_det": ["CO leak alarm", "CO noplūde"],
    "co_leak": ["CO leak alarm", "CO noplūde"],
    "blowdown_tank": ["blowdown tank", "nopūšanas tvertne"],
    "bottom_blowdown": ["bottom blowdown", "apakšējā nopūšana"],
    "safety_bypass": ["safety bypass", "drošības apeja"],
    "burner_safety": ["burner safety chain", "katla drošības ķēde"],
    "pumps_safety": ["pumps safety chain", "sūkņu drošības ķēde"],
    "enable_vs": ["output pasivated", "izeja pasivēta"],
    "dif_p": ["differential pressure", "diferenciālais spiediens"],
    "no_press_generated_error": ["no pressure generated", "nerada spiedienu"],
    "feedback_error": ["feedback error", "atpakaļsaites kļūda"],
    "nw_side": ["network side", "tīklu puse"],
    "boiler_side": ["boiler side", "katlu puse"],
    "move_check": ["move check", "kustības pārbaude"],
    "nw_circuit": ["network circuit", "tīklu loks"],
    "network_circuit": ["network circuit", "tīklu loks"],
    "pressure_drop": ["pressure drop", "spiediena nomešana"],
    "heat_pumps": ["heat pumps", "siltumsukņi"],
    "heat_pump": ["heat pump", "siltumsūknis"],
    "air_heater": ["air heater", "gaisa silditajs"],
    "dry_coolers": ["dry coolers", "dzesētāji"],
    "dry_cooler": ["dry cooler", "dzesētājs"],
    "cold_side": ["cold side", "aukstā puse"],
    "warm_side": ["warm side", "siltā puse"],
    "pos_fault": ["positionning error", "pozīcijas kļūda"],
    "el_meters": ["electrical meters", "elektrības skaitītāji"],
    "el_meter": ["electrical meter", "elektrības skaitītājs"],
    "diagnostics_module_states": ["", ""],
    "ai_fault": ["analog signal fault", "analogā signāla kļūda"],
    "high_pwr_alarm": ["high power alarm", "augstas jaudas kļūda"],
    "high_pwr_warning": ["high power warning", "augstas jaudas brīdinājums"],
     "on_CMD": ["active", "aktīvs"],
     "auto_pwr_limit": ["automatic power limitation", "automātiska jaudas ierobežošana"],
     "output_at_max": ["output at max value", "izeja maksimāla vērtība"],
     "cnt_change_event": ["count changed", "skaita izmaiņa"],
     "Event_DB": ["", ""],
     "Event DB": ["", ""],
     "alarms_warnings_gd\".": ["", ""],
     "alarms_warnings_gd": ["", ""],

    
}

generic_words = {
    "nw": ["network", "tīkli"],
    "udt": ["", ""],
    "db": ["", ""],
    "opened": ["opened", "atvērts"],
    "closed": ["closed", "aizvērts"],
    "running": ["running", "darbā"],
    "radiator": ["radiator", "radiators"],
    "bypass": ["bypass", "apeja"],
    "side": ["side", "puse"],
    "cooler": ["cooler", "dzesētājs"],
    "coolers": ["coolers", "dzesētāji"],
    "socket": ["socket", "rozete"],
    "sockets": ["sockets", "rozetes"],
    "fuse": ["fuse", "drošinātājs"],
    "rs485": ["RS485", "RS485"],
    "RS485": ["RS485", "RS485"],
    "klin": ["klin", "kalte"],
    "kiln": ["klin", "kalte"],
    "drop": ["drop", "nomešanas"],


    "3way": ["3 way", "trīsceļu"],
    "return": ["return", "atgaita"],
    "inlet": ["inlet", "ieeja"],
    "outlet": ["outlet", "izeja"],
    "supply": ["supply", "turpgaita"],
    "heating": ["heating", "sildīšana"],
    "water": ["water", "ūdens"],
    "before": ["before", "pirms"],
    "burner": ["burner", "deglis"],
    "hm": ["heat meter", "siltumskaitītājs"],
    "boiler": ["boiler", "katls"],
    "glycol": ["glycol", "glikols"],
    "room": ["room", "telpa"],
    "filtering": ["filtering", "filtrācijas"],
    "filter": ["filter", "filtrs"],
    "oil": ["oil", "eļļa"],
    "circuit": ["circuit", "loks"],
    "circulation": ["circulation", "cirkulācijas"],
    "circ": ["circulation", "cirkulācijas"],
    "pumps": ["pumps", "sūkņi"],
    "pump": ["pump", "sūknis"],
    "estop": ["emergency stop button", "avārijas stop poga"],
    "enclosure": ["enclosure", "sadale"],
    "ext": ["external", "ārēja"],
    "winter": ["winter", "ziemas"],
    "summer": ["summer", "vasaras"],
    "dosing": ["dosing", "dozācijas"],
    "vlvs": ["valves", "vārsti"],
    "vlv": ["valve", "vārsts"],
    "other": ["other", "citi"],
    "line_1": ["line 1", "līnija 1"],
    "line_2": ["line 2", "līnija 2"],
    "line_3": ["line 3", "līnija 3"],
    "line_4": ["line 4", "līnija 4"],
    "line_5": ["line 5", "līnija 5"],
    "tank_1": ["tank 1", "tvertne 1"],
    "tank_2": ["tank 2", "tvertne 2"],
    "tank_3": ["tank 3", "tvertne 3"],
    "tank_4": ["tank 4", "tvertne 4"],
    "tank_5": ["tank 5", "tvertne 5"],
    "line1": ["line 1", "līnija 1"],
    "line2": ["line 2", "līnija 2"],
    "line3": ["line 3", "līnija 3"],
    "line4": ["line 4", "līnija 4"],
    "line5": ["line 5", "līnija 5"],
    "tank1": ["tank 1", "tvertne 1"],
    "tank2": ["tank 2", "tvertne 2"],
    "tank3": ["tank 3", "tvertne 3"],
    "tank4": ["tank 4", "tvertne 4"],
    "tank5": ["tank 5", "tvertne 5"],
    "rdy": ["fault", "bojājums"],
    "alarms": ["fault", "bojājums"],
    "alarm": ["fault", "bojājums"],
    "hla": ["high level alarm", "augsta līmeņa trauksme"],
    "lla": ["low level alarm", "zema līmeņa trauksme"],
    "hl": ["high level", "augsts līmenis"],
    "ll": ["low level", "zems līmenis"],
    "switch": ["switch", "slēdzis"],
    "sw": ["switch", "slēdzis"],
    "pid": ["PID controller", "PID kontrolleris"],
    "cntrl": ["control", "vadība"],
    "lvl": ["level", "līmenis"],
    "feed": ["feed", "barošanas"],
    "leakage": ["leakage", "noplūde"],
    "failure": ["failure", "bojājums"],
    "input": ["input", "ieeja"],
    "output": ["output", "izeja"],
    "filling": ["filling", "pildīšana"],
    "fill": ["filling", "pildīšana"],
    "after": ["after", "pēc"],
    "fluegas": ["fluegas", "dūmgāzes"],
    "ventilator": ["ventilator", "ventilators"],
    "transport": ["transport", "transports"],
    "shutoff": ["shutoff", "noslēgvārsts"],
    "collector": ["collector", "kolektors"],
    "deair": ["deairing", "atgaisošana"],
    "mdi": ["MDI", "MDI"],
    "polyol": ["polyol", "poliols"],
    "recirculation": ["recirculation", "recirculation"],
    "hot": ["hot", "karstais"],
    "cold": ["cold", "aukstais"],
    "24vdc": ["24V", "24V"],
    "24v": ["24V", "24V"],
    "on": ["off", "izslēgts"],
    "deironer": ["deironer", "atdzelžotājs"],
    "manufacturing": ["manufacturing", "ražošana"],
    "to": ["to", "uz"],
    "condensate": ["condensate", "kondensāts"],
    "scale": ["scale", "svari"],
    "heaters": ["heaters", "sildītāji"],
    "heater": ["heater", "sildītājs"],
    "he_1": ["heat exchanger 1", "siltummainis 1"],
    "he_2": ["heat exchanger 2", "siltummainis 2"],
    "he_3": ["heat exchanger 3", "siltummainis 3"],
    "he_4": ["heat exchanger 4", "siltummainis 4"],
    "he_5": ["heat exchanger 5", "siltummainis 5"],
    "he1": ["heat exchanger 1", "siltummainis 1"],
    "he2": ["heat exchanger 2", "siltummainis 2"],
    "he3": ["heat exchanger 3", "siltummainis 3"],
    "he4": ["heat exchanger 4", "siltummainis 4"],
    "he5": ["heat exchanger 5", "siltummainis 5"],
    "warning": ["warning", "brīdinājums"],
    "fault": ["fault", "kļūda"],
    "ready": ["not ready", "nav gatavībā"],
    "running": ["running", "darbā"],
    "tanks": ["tanks", "tvertnes"],
    "tank": ["tank", "tvertne"],
    "ro": ["reverse osmosis", "reversā osmoze"],
    "e_stop": ["emergency stop", "avārijas stop"],
    "fwt": ["fresh water tank", "sagatavotā ūdens tvertne"],
    "thermostat": ["thermostat", "termostats"],
    "outside": ["outside", "ārgaisa"],
    "out": ["output", "izeja"],
    "conductivity": ["conductivity", "vadītspēja"],
    "cooling": ["cooling", "dzesēšana"],
    "fan": ["fan", "ventilators"],
    "cmd": ["command", "komanda"],
    "req": ["request", "pieprasījums"],
    "backup": ["backup", "rezerves"],
    "prealarm": ["prealarm", "brīdinājums"],
    "hp": ["heat pump", "siltumsūknis"],
    "warm": ["warm", "silts"],
    "he": ["heat exchanger", "siltummainis"],
    "for": ["for", "priekš"],
    "ON": ["on", "ieslēgts"],
    "on": ["on", "ieslēgts"],
    "fb": ["feedback", "atpakaļsaite"],
    "FB": ["feedback", "atpakaļsaite"],
    "bh": ["boiler house", "katlu māja"],
    "di1": ["digital inputs 1", "digitālās ieejas 1"],
    "di2": ["digital inputs 2", "digitālās ieejas 2"],
    "di3": ["digital inputs 3", "digitālās ieejas 3"],
    "DB": ["", ""],

}

sensor_types = {
    "press_dif_": ["Diferential pressure", "Diferenciālais spiediens"],
    "dif_p": ["Diferential pressure", "Diferenciālais spiediens"],
    "press_": ["Pressure", "Spiediens"],
    "lvl_": ["Level", "Līmenis"],
    "t_": ["Temperature", "Temperatūra"],
    "flow_": ["Flow", "Plūsma"],
    "vibr_": ["Vibration", "Vibrācija"],
    "voltage": ["Voltage", "Spriegums"],
    "volt_": ["Voltage", "Spriegums"],
    "voltage_24vdc": ["Voltage 24V", "Spriegums 24V"],
    "volt_24vdc": ["Voltage 24V", "Spriegums 24V"],
    "conductivity": ["Conductivity", "vadītspēja"],
    "pwr_nw": ["Power", "jauda"], # Kaut kam jābūt galā savādāk paņem visas 24V barošanas trauksmes
}

sensor_alarms = {
    "PV_LLA_E": ["low level alarm", "zema līmeņa trauksme"],
    "PV_LA_E": ["low level warning", "zema līmeņa brīdinajums"],
    "PV_LL_E": ["low level warning", "zema līmeņa brīdinajums"],
    "PV_HA_E": ["high level warning", "augsta līmeņa brīdinajums"],
    "PV_HL_E": ["high level warning", "augsta līmeņa brīdinajums"],
    "PV_HLA_E": ["high level alarm", "augsta līmeņa trauksme"],
    "PEW_ERR": ["sensor error", "mērijuma kļūda"]
}

power_alarms = {
    "mains_ok": ["Mains power fault", "Maiņsprieguma bojājums"],
    "mains_rdy": ["Mains power fault", "Maiņsprieguma bojājums"],
    "mains_OK": ["Mains power fault", "Maiņsprieguma bojājums"],
    "mains_RDY": ["Mains power fault", "Maiņsprieguma bojājums"],
    "mains_voltage_OK": ["Mains power fault", "Maiņsprieguma bojājums"],
    "24vdc_redundancy_A_ok": ["24V redundancy momdule failure A", "24V redundance bojājums A"],
    "24vdc_redundancy_B_ok": ["24V redundancy momdule failure B", "24V redundance bojājums B"],
    "24v_redundancy_a_ok": ["24V redundancy momdule failure A", "24V redundance bojājums A"],
    "24v_redundancy_b_ok": ["24V redundancy momdule failure B", "24V redundance bojājums B"],
    "24v_redundancy_A_ok": ["24V redundancy momdule failure A", "24V redundance bojājums A"],
    "24v_redundancy_B_ok": ["24V redundancy momdule failure B", "24V redundance bojājums B"],
    "24vdc_24V": ["24V chain failure", "24V sprieguma bojājums"],
    "24v_ok": ["24V chain failure", "24V sprieguma bojājums"],
    "24V_ok": ["24V chain failure", "24V sprieguma bojājums"],
    "24vdc_24V1": ["24V1 chain failure", "24V1 sprieguma bojājums"],
    "24vdc_24V2": ["24V2 chain failure", "24V2 sprieguma bojājums"],
    "24vdc_24V3": ["24V3 chain failure", "24V3 sprieguma bojājums"],
    "24v_24V": ["24V chain failure", "24V sprieguma bojājums"],
    "24v_24V1": ["24V1 chain failure", "24V1 sprieguma bojājums"],
    "24v_24V2": ["24V2 chain failure", "24V2 sprieguma bojājums"],
    "24v_24V3": ["24V3 chain failure", "24V3 sprieguma bojājums"],
    "24v_24V4": ["24V4 chain failure", "24V4 sprieguma bojājums"],
    "24v_24V5": ["24V5 chain failure", "24V5 sprieguma bojājums"],
    "24v_24V6": ["24V6 chain failure", "24V6 sprieguma bojājums"],
    "24v_24V7": ["24V7 chain failure", "24V7 sprieguma bojājums"],
    "24v_24V8": ["24V8 chain failure", "24V8 sprieguma bojājums"],
    "24v_24V9": ["24V9 chain failure", "24V9 sprieguma bojājums"],
    "24v_24V10": ["24V10 chain failure", "24V10 sprieguma bojājums"],
    "24V1_ok": ["24V1 chain failure", "24V1 sprieguma bojājums"],
    "24V2_ok": ["24V2 chain failure", "24V2 sprieguma bojājums"],
    "24V3_ok": ["24V3 chain failure", "24V3 sprieguma bojājums"],
    "24V1_OK": ["24V1 chain failure", "24V1 sprieguma bojājums"],
    "24V2_OK": ["24V2 chain failure", "24V2 sprieguma bojājums"],
    "24V3_OK": ["24V3 chain failure", "24V3 sprieguma bojājums"],
    "24v1_ok": ["24V1 chain failure", "24V1 sprieguma bojājums"],
    "24v2_ok": ["24V2 chain failure", "24V2 sprieguma bojājums"],
    "24v3_ok": ["24V3 chain failure", "24V3 sprieguma bojājums"],
    "24v4_ok": ["24V4 chain failure", "24V4 sprieguma bojājums"],
    "24v5_ok": ["24V5 chain failure", "24V5 sprieguma bojājums"],
    "24v6_ok": ["24V6 chain failure", "24V6 sprieguma bojājums"],
    "24v7_ok": ["24V7 chain failure", "24V7 sprieguma bojājums"],
    "24v8_ok": ["24V8 chain failure", "24V8 sprieguma bojājums"],
    "24v9_ok": ["24V9 chain failure", "24V9 sprieguma bojājums"],
    "24v10_ok": ["24V10 chain failure", "24V10 sprieguma bojājums"],
    "external_24V1_OK": ["24V1 external chain failure", "24V1 ārējā sprieguma bojājums"],
    "external_24V2_OK": ["24V2 external chain failure", "24V2 ārējā sprieguma bojājums"],
    "external_24V3_OK": ["24V3 external chain failure", "24V3 ārējā sprieguma bojājums"],
    "DC_ok": ["DC power fault", "24V barošanas bojājums"],
    "24_ok": ["DC power fault", "24V barošanas bojājums"],
    "bat_fail": ["battery fault", "baterijas bojājums"],
    "24v_ups_dc_ok": ["24VDC UPS fault", "24V UPS bojājums"],
    "24vdc_ups_dc_ok": ["24VDC UPS fault", "24V UPS bojājums"],
    "24v_ups_bat_fail": ["24VDC UPS battery fault", "24V UPS baterijas bojājums"],
    "24vdc_ups_bat_fail": ["24VDC UPS battery fault", "24V UPS baterijas bojājums"],
    "24V_ups_bat_fail": ["24VDC UPS battery fault", "24V UPS baterijas bojājums"],
    "high_pwr_alarm": ["high power alarm", "augstas jaudas kļūda"],
    "high_pwr_warning": ["high power warning", "augstas jaudas brīdinājums"],
}

device_alarms = {
    "vfd_on": ["VFD off", "VFD izslēgts"],
    "fault_vfd": ["VFD fault", "FP bojājums"],
    "rdy": ["fault", "bojājums"],
    "move_fault": ["control fault", "vadības kļūda"],
    "move_flt": ["control fault", "vadības kļūda"],
    "cntrl_flt": ["control fault", "vadības kļūda"],
    "cntrl_fault": ["control fault", "vadības kļūda"],
    "fb_err": ["feedback error", "atpakaļsaites bojājums"],
    "fb_error": ["feedback error", "atpakaļsaites bojājums"],
    "FB_err": ["feedback error", "atpakaļsaites bojājums"],
    "warning_fault": ["warning", "brīdinājums"],
    "warning": ["warning", "brīdinājums"],
    "com_ok": ["communications fault", "komunikācijas kļūda"],
    "fault": ["fault", "kļūda"],
    "local_remote": ["local control enabled", "ieslēgta lokāla vadība"],
    "loc_rem": ["local control enabled", "ieslēgta lokāla vadība"],
    "run_enable_missing": ["run enable missing", "nav atļaujas signāla"],
    "run_enable": ["run enable missing", "nav atļaujas signāla"],
    "cntrl\".man_out_enable": ["manual output enabled", "rokas izejas vadība"],
    ".man_out_enable": ["manual output enabled", "rokas izejas vadība"],
    "vfd_fieldbus_adapter_fault": ["VFD fieldbus adapter fault", "FP komunikācijas moduļa kļūda"],
    "state_fault": ["state fault", "pozīcijas kļūda"],
    "opened": ["opened", "atvērts"],
    "closed": ["closed", "aizvērts"],
    "running": ["running", "darbā"],
    "PEW_ERR": ["sensor error", "mērijuma kļūda"],
    "pos_fault": ["positionning error", "pozīcijas kļūda"]
}

"""
AlarmType.DIGITAL_SENSOR_ALARM: ["sw_","lvl_sw_", "t_sw_", "press_sw_"],
"""
digital_sensor_alarms = {
    "sw_press_max": ["high pressure switch", "augsta spiediena slēdzis"],
    "sw_press_min": ["low pressure switch", "zema spiediena slēdzis"],
    "sw_t_max": ["high temperature switch", "augstas temperatūras slēdzis"],
    "sw_t_min": ["low temperature switch", "zemas temperatūras slēdzis"],
    "lvl_sw_": ["level switch", "līmeņa slēdzis"],
    "t_sw_": ["temperature switch", "temperatūras slēdzis"],
    "press_sw_": ["pressure switch", "spiediena slēdzis"],
}

ALARM_TAG_TO_TYPE_DICT = {
    AlarmType.DIGITAL_SENSOR_ALARM: [key for key in digital_sensor_alarms.keys()],
    #AlarmType.SENSOR_ALARM: ["t_", "press_", "flow_", "lvl_", "dif_p", "volt_", "voltage_", "vibr_"],
    AlarmType.SENSOR_ALARM: [key for key in sensor_types.keys()],
    AlarmType.DEVICE_ALARM: ["vlv_", "pump_", "vlvs_"],
    AlarmType.POWER_ALARM: ["pwr_"],
}

place_holder_text = ["empty", "false", "always_false", "a", "Discrete alarm"]
